driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-16.04
    run_list:
    - recipe[apt::default]
  - name: centos-6.8
    run_list:
    - recipe[yum::default]

suites:
  - name: default
    run_list:
      - recipe[drbd::default]
